### ISSUE TITLE
Create separate sub-projects for planning, adaptation and execution

### ISSUE THREAD

**Issue by rju** [research-iobserve/iobserve-analysis#41]
Currently the analysis sub project contains all sorts of code which does not belong to the analysis service. Unfortunately, they are packed in the same org.iobserve.analysis. To fix this issue, I propose to move them to separate projects which would also allow to really create executables for planning and adaptation.

What to do:
* Create a new directory for planning, adaptation and execution
* Copy the build.gradle from analysis.cli to all these directories and adjust the parameters
* Add the directories to the settings.gradle file (after all the library components)
* Re-import the gradle main project in Eclipse this will automatically import the new directories as empty projects
* Create a src/main/java and src/test/java source folder in each project
* Move packages within Eclipse from analysis to the respective projects
* Fix the dependencies in the build.gradle file if necessary

**Comment by rju** [comment]
This issue is related to #5

**Comment by LarsBluemke** [comment]
Jobs done
